modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="ode_to_satellite_and_shark"
version="1.0.2"
displayName="Ode to Satellite and Shark"
displayURL="https://github.com/tiankers/Ode-to-Satellite-and-Shark"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Tianker"
description="Ode to Satellite and Shark"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.ode_to_satellite_and_shark]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.232,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ode_to_satellite_and_shark]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ode_to_satellite_and_shark]]
    modId="curios"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ode_to_satellite_and_shark]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration